version: '3.3'
services:
  db:
    image: postgres:15.1-alpine
    container_name: e-commerce
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/e-commerce
volumes:
  db:
    driver: local